### ISSUE TITLE
It can scrap only 1 page of the website

### ISSUE THREAD

**Issue by SoulReaper5225** [jjnanthakumar/Udemy-Coupon-Scraping#1]
The code is working well. The only issue is it can search only 1 page from the coupon website. If possible can you modify the code so that it can search on multiple pages of the website?

**Comment by jjnanthakumar** [comment]
One Page are you sure?

**Comment by jjnanthakumar** [comment]
Actually, there are two domain URLs, one will work fine and can scrape up to n number of pages. (techitweets domain)

**Comment by SoulReaper5225** [comment]
okay

**Comment by jjnanthakumar** [comment]
Don't worry ASAP I will convert this into web app.. 
Please star this repo if you found this useful.
